### ISSUE TITLE
LtrDigest Missing a Flag

### ISSUE THREAD

**Issue by bioinfo-Kacst** [mcsimenc/PhyLTR#27]
-trnas flag in LtrDigest its important for for PBS detection

Because PBSs are identified by detecting regions complementary to host tRNA. This process requires a tRNA sequence library T. Such a library can be predicted from the genomic sequence with high accuracy, e.g. using tRNAscan-SE (23). To model the complementarity of a tRNA t ∈ T and a putative PBS on the retrotransposon sequence, the reverse complement of t (to be supplied in 5′–3′ direction) is locally aligned to the genomic sequence.

**Comment by mcsimenc** [comment]
-trnas is for supplying a user-specified set of trna sequences.
