### ISSUE TITLE
Dfam setup issue

### ISSUE THREAD

**Issue by conte1** [mcsimenc/PhyLTR#30]
Hi,

I am following the installation instructions but running into a problem during this Dfam step:

`C. Run: PhyLTR/scripts/DfamHMM2SuperFamTable.py < Dfam_ERV_LTR.hmm > Dfam_ERV_LTR.SF`

This produces an empty file. Upon further inspection it appears that starting with Dfam 3.0, the structure of the Dfam.hmm.gz file changed to something like this which breaks the previous DfamExtractLTRelements.py script:
`CT    Interspersed_Repeat;Transposable_Element;Retrotransposed_Element;Retrotransposon;Long_Terminal_Repeat_Element;Bel-Pao
`
Downloading of Dfam 2.0 starts to get around the problem, but the DfamExtractLTRelements.py script does not output all three CT lines that are expected by the DfamHMM2SuperFamTable.py script, so the CT Superfamily lines get lost and nothing is output.

I think it would be a simple fix to the python code, but I wanted to make sure I wasn't doing something else wrong.

Thanks,
Matt

**Comment by mcsimenc** [comment]
Hi Matt,

Thanks for finding this problem. I updated the scripts and they should work with Dfam 3.x now.

Matt

**Comment by gnmcsbnfrmtcsclb** [comment]
@conte1 - have you had successful runs using PhyLTR? If yes, could you share via Google Drive or FTP download link a zipped folder of your output from such a successful run, please?

In our PhyLTR runs, the later steps do not seem to produce results. For example, it says 
**1.** Modeltest/NoGCFiltering/NO_MODEL_TESTING_DONE,
**2.** the entire MCL output subfolder is not created, and 
**3.** though the folders below are created, they are all empty!
GENECONV/ERV1/g0:
GENECONV/ERV1/g1:
GENECONV/ERV1/g2:
GENECONV/ERV2/g0:
GENECONV/ERV2/g1:
GENECONV/ERV2/g2:
GENECONV/Gypsy/g0:
GENECONV/Gypsy/g1:
GENECONV/Gypsy/g2:
Thank you in advance!
